const curriculumTopics = [
  "Day 1: Greeting friends at school",
  "Day 2: Introducing yourself",
  "Day 3: Talking about your favorite color",
  "Day 4: Counting things in your room",
  "Day 5: My family members",
  "Day 6: What I eat for breakfast",
  "Day 7: Lunch menu talk",
  "Day 8: My favorite fruit",
  "Day 9: My favorite animal",
  "Day 10: Pets at home",
  "Day 11: My school bag items",
  "Day 12: Classroom objects",
  "Day 13: My best friend",
  "Day 14: Weekend plans",
  "Day 15: My favorite game",
  "Day 16: Playground activities",
  "Day 17: Weather today",
  "Day 18: Seasons I like",
  "Day 19: Clothes for each season",
  "Day 20: My daily routine",
  "Day 21: Morning habits",
  "Day 22: After-school activities",
  "Day 23: Bedtime routine",
  "Day 24: My favorite book",
  "Day 25: Story characters",
  "Day 26: Library visit",
  "Day 27: My favorite cartoon",
  "Day 28: Movie night",
  "Day 29: Music I like",
  "Day 30: Singing a simple song",
  "Day 31: Musical instruments",
  "Day 32: Sports I play",
  "Day 33: Soccer talk",
  "Day 34: Swimming day",
  "Day 35: Riding a bike",
  "Day 36: Healthy food choices",
  "Day 37: Drinking water",
  "Day 38: Visiting a doctor",
  "Day 39: Feeling sick",
  "Day 40: Feelings and emotions",
  "Day 41: Happy moments",
  "Day 42: Sad moments",
  "Day 43: Being kind",
  "Day 44: Helping parents",
  "Day 45: House chores",
  "Day 46: My room cleanup",
  "Day 47: Birthday party",
  "Day 48: Birthday gifts",
  "Day 49: Holiday plans",
  "Day 50: Going to the beach",
  "Day 51: Going camping",
  "Day 52: Visiting grandparents",
  "Day 53: Traveling by bus",
  "Day 54: Traveling by train",
  "Day 55: Airport conversation",
  "Day 56: Asking for directions",
  "Day 57: In the supermarket",
  "Day 58: At the bakery",
  "Day 59: At the restaurant",
  "Day 60: Ordering drinks",
  "Day 61: At the zoo",
  "Day 62: At the park",
  "Day 63: At the museum",
  "Day 64: At the aquarium",
  "Day 65: Nature walk",
  "Day 66: Trees and flowers",
  "Day 67: Rainy day fun",
  "Day 68: Snowy day fun",
  "Day 69: My favorite toy",
  "Day 70: Sharing toys",
  "Day 71: Building blocks",
  "Day 72: Drawing pictures",
  "Day 73: Making crafts",
  "Day 74: Cooking with family",
  "Day 75: Simple recipe",
  "Day 76: School lunch talk",
  "Day 77: Class presentation",
  "Day 78: Asking questions",
  "Day 79: Answering politely",
  "Day 80: Saying thank you",
  "Day 81: Apologizing politely",
  "Day 82: Making requests",
  "Day 83: Giving permission",
  "Day 84: Talking about time",
  "Day 85: Telling the date",
  "Day 86: Calendar events",
  "Day 87: My dream job",
  "Day 88: Community helpers",
  "Day 89: Fire safety basics",
  "Day 90: Road safety",
  "Day 91: Internet safety",
  "Day 92: Saving money",
  "Day 93: Good study habits",
  "Day 94: Teamwork",
  "Day 95: School festival",
  "Day 96: Talent show",
  "Day 97: New year goals",
  "Day 98: Review my progress",
  "Day 99: My proud moment",
  "Day 100: Free talking challenge"
];
